import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useSelector } from 'react-redux';

export default function Home() {
  const user = useSelector(store => store.user);
  const theme = useSelector(store => store.theme);

  console.log(user, theme)
  return (
    <>
      <Head>
        <title>Habitual</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Habitual</h1>
      </main>
    </>
  )
}
