import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Habitual</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <h1>Habitual</h1>
        <h2>Track your habits</h2>
        <p>
          Habitual is a habit tracking app that allows you to track your habits
          and see your progress over time.
        </p>
      
    </>
  );
}
